<?php
defined( 'ABSPATH' ) || exit;

final class PIPO_GD_Engine implements ImageEngineInterface {
	private $image; private $mime; private $quality = 82; private $orientation = 1;
	public function name() { return 'gd'; }
	public function is_available() { return extension_loaded( 'gd' ) && function_exists( 'gd_info' ); }
	public function supports_mime( $mime ) { return isset( $this->loaders()[ $mime ] ) && function_exists( $this->loaders()[ $mime ][0] ) && function_exists( $this->loaders()[ $mime ][1] ); }
	private function loaders() { return array( 'image/jpeg' => array( 'imagecreatefromjpeg', 'imagejpeg' ), 'image/png' => array( 'imagecreatefrompng', 'imagepng' ), 'image/gif' => array( 'imagecreatefromgif', 'imagegif' ), 'image/webp' => array( 'imagecreatefromwebp', 'imagewebp' ), 'image/avif' => array( 'imagecreatefromavif', 'imageavif' ) ); }
	public function load( $path ) { $info = @getimagesize( $path ); if ( ! $info || ! $this->supports_mime( $info['mime'] ) ) { throw new RuntimeException( 'gd_load_unsupported' ); } $fn = $this->loaders()[ $info['mime'] ][0]; $this->image = @$fn( $path ); if ( ! $this->image ) { throw new RuntimeException( 'gd_load_failed' ); } $this->mime = $info['mime']; if ( 'image/jpeg' === $this->mime && function_exists( 'exif_read_data' ) ) { $exif = @exif_read_data( $path ); $this->orientation = is_array( $exif ) && isset( $exif['Orientation'] ) ? (int) $exif['Orientation'] : 1; } return $this; }
	public function dimensions() { return array( 'width' => imagesx( $this->image ), 'height' => imagesy( $this->image ) ); }
	private function canvas( $width, $height ) { $canvas = imagecreatetruecolor( $width, $height ); if ( in_array( $this->mime, array( 'image/png', 'image/webp', 'image/avif', 'image/gif' ), true ) ) { imagealphablending( $canvas, false ); imagesavealpha( $canvas, true ); $transparent = imagecolorallocatealpha( $canvas, 0, 0, 0, 127 ); imagefill( $canvas, 0, 0, $transparent ); } return $canvas; }
	public function resize( $max_width, $max_height ) { $d = $this->dimensions(); $scale = min( 1, $max_width / $d['width'], $max_height / $d['height'] ); $w = max( 1, (int) round( $d['width'] * $scale ) ); $h = max( 1, (int) round( $d['height'] * $scale ) ); if ( $w === $d['width'] && $h === $d['height'] ) { return $this; } $new = $this->canvas( $w, $h ); imagecopyresampled( $new, $this->image, 0, 0, 0, 0, $w, $h, $d['width'], $d['height'] ); imagedestroy( $this->image ); $this->image = $new; return $this; }
	public function crop( $x, $y, $width, $height, $target_width = null, $target_height = null ) { $tw = $target_width ?: $width; $th = $target_height ?: $height; $new = $this->canvas( $tw, $th ); if ( ! imagecopyresampled( $new, $this->image, 0, 0, $x, $y, $tw, $th, $width, $height ) ) { throw new RuntimeException( 'gd_crop_failed' ); } imagedestroy( $this->image ); $this->image = $new; return $this; }
	public function compress( $quality ) { $this->quality = max( 1, min( 100, (int) $quality ) ); return $this; }
	public function configure( $options ) { if ( ! empty( $options['lossless'] ) ) { throw new RuntimeException( 'gd_lossless_not_guaranteed' ); } if ( ! empty( $options['preserve_icc'] ) ) { throw new RuntimeException( 'gd_icc_preservation_unavailable' ); } return $this; }
	public function change_format( $mime ) { if ( ! $this->supports_mime( $mime ) ) { throw new RuntimeException( 'gd_format_unsupported' ); } $this->mime = $mime; return $this; }
	public function strip_metadata( $options = array() ) { if ( ! empty( $options['preserve_copyright'] ) ) { throw new RuntimeException( 'gd_copyright_preservation_unavailable' ); } return $this; }
	public function normalize_orientation() { if ( in_array( $this->orientation, array( 2, 4, 5, 7 ), true ) && function_exists( 'imageflip' ) ) { imageflip( $this->image, IMG_FLIP_HORIZONTAL ); } $angles = array( 3 => 180, 4 => 180, 5 => -90, 6 => -90, 7 => 90, 8 => 90 ); if ( isset( $angles[ $this->orientation ] ) ) { $rotated = imagerotate( $this->image, $angles[ $this->orientation ], 0 ); if ( $rotated ) { imagedestroy( $this->image ); $this->image = $rotated; } } $this->orientation = 1; return $this; }
	public function save( $path ) { $fn = $this->loaders()[ $this->mime ][1]; if ( 'image/png' === $this->mime ) { $ok = $fn( $this->image, $path, (int) round( 9 - ( $this->quality / 100 * 9 ) ) ); } elseif ( 'image/gif' === $this->mime ) { $ok = $fn( $this->image, $path ); } else { $ok = $fn( $this->image, $path, $this->quality ); } if ( ! $ok ) { throw new RuntimeException( 'gd_save_failed' ); } return $path; }
}
